-- ════════════════════════════════════════════════════════════════════════════
-- FlowOps V2 — Database Schema
-- Target: Supabase (PostgreSQL 15+)
-- RLS: intentionally disabled — add before going to production
-- ════════════════════════════════════════════════════════════════════════════

-- ── Extensions ────────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- gen_random_uuid()




-- ── Readable code sequences ───────────────────────────────────────────────────
-- Generates codes like DEL-0001, RC-0043 at the DB level.
-- Avoids race conditions that happen when two clients compute the next
-- counter at the same time and both insert the same code.

CREATE SEQUENCE IF NOT EXISTS delivery_code_seq
  START  1 INCREMENT 1 MINVALUE 1 NO MAXVALUE CACHE 1;

-- Start at 43 to match existing seed data (RC-0038, RC-0041, RC-0042 exist).
CREATE SEQUENCE IF NOT EXISTS rack_code_seq
  START 43 INCREMENT 1 MINVALUE 1 NO MAXVALUE CACHE 1;


-- ── Shared trigger: auto-update updated_at ────────────────────────────────────

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


-- ════════════════════════════════════════════════════════════════════════════
-- TABLE: zones
-- Physical areas of the warehouse floor (A1, B2, OVF, etc.)
-- Referenced by racks.  No updated_at — zones rarely change.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS zones (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name          text        NOT NULL UNIQUE,
  label         text,                                -- "Receiving dock", "Lotting tables"
  capacity      integer     CHECK (capacity IS NULL OR capacity > 0),
  reserved      boolean     NOT NULL DEFAULT false, -- true = zone held but not yet assigned to a delivery
  auction_color text,                              -- hex color; when set, shows a color dot on the cell
  auction_date  text,                              -- YYYY-MM-DD; shown on auction cells without a linked delivery
  created_at    timestamptz NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  zones          IS 'Physical warehouse floor areas.';
COMMENT ON COLUMN zones.name     IS 'Short code shown to workers: A1, B2, OVF.';
COMMENT ON COLUMN zones.capacity IS 'Max racks before a warning is shown. NULL = unlimited.';


-- ════════════════════════════════════════════════════════════════════════════
-- TABLE: deliveries
-- A shipment from a consigner — contains one or more racks.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS deliveries (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  delivery_code       text        NOT NULL UNIQUE
                                  DEFAULT 'DEL-' || LPAD(nextval('delivery_code_seq')::text, 4, '0'),
  consigner_name      text        NOT NULL,
  expected_rack_count integer     NOT NULL DEFAULT 0 CHECK (expected_rack_count >= 0),
  type                text        NOT NULL
                                  CHECK (type IN ('scheduled', 'walkin')),
  status              text        NOT NULL DEFAULT 'scheduled'
                                  CHECK (status IN ('scheduled', 'arrived', 'processing', 'complete')),
  scheduled_date      date        NOT NULL,
  arrived_at          timestamptz,
  completed_at        timestamptz,
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT NOW(),
  updated_at          timestamptz NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS deliveries_set_updated_at ON deliveries;
CREATE TRIGGER deliveries_set_updated_at
  BEFORE UPDATE ON deliveries
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE  deliveries                  IS 'Incoming shipments from consigners.';
COMMENT ON COLUMN deliveries.delivery_code    IS 'Human-readable code auto-generated by sequence.';
COMMENT ON COLUMN deliveries.expected_rack_count IS '0 = unknown (typical for walk-ins).';
COMMENT ON COLUMN deliveries.type            IS '"walkin" skips scheduled status; starts as arrived.';


-- ════════════════════════════════════════════════════════════════════════════
-- TABLE: racks
-- A single physical rack moving through the warehouse pipeline.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS racks (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  rack_code      text        NOT NULL UNIQUE
                             DEFAULT 'RC-' || LPAD(nextval('rack_code_seq')::text, 4, '0'),
  consigner_name text        NOT NULL,
  status         text        NOT NULL DEFAULT 'unpacking_sorting'
                             CHECK (status IN ('unpacking_sorting', 'sorted', 'lotting', 'ready', 'pickup', 'completed')),
  priority       text        NOT NULL DEFAULT 'normal'
                             CHECK (priority IN ('high', 'normal', 'low')),

  -- SET NULL so that deleting a zone or delivery does not cascade-delete racks.
  zone_id        uuid        REFERENCES zones(id)      ON DELETE SET NULL,
  delivery_id    uuid        REFERENCES deliveries(id)  ON DELETE SET NULL,

  notes          text,
  created_at     timestamptz NOT NULL DEFAULT NOW(),
  updated_at     timestamptz NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS racks_set_updated_at ON racks;
CREATE TRIGGER racks_set_updated_at
  BEFORE UPDATE ON racks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE  racks             IS 'Physical racks moving through the processing pipeline.';
COMMENT ON COLUMN racks.rack_code   IS 'Human-readable code auto-generated by sequence.';
COMMENT ON COLUMN racks.status      IS 'Current processing stage.';
COMMENT ON COLUMN racks.zone_id     IS 'Physical floor location. Independent of status.';
COMMENT ON COLUMN racks.delivery_id IS 'The delivery this rack arrived with.';


-- ════════════════════════════════════════════════════════════════════════════
-- TABLE: rack_events
-- Immutable audit log of every status transition.
-- Used by lib/timeTracking.ts to compute time-per-stage and stuck detection.
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS rack_events (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  rack_id     uuid        NOT NULL REFERENCES racks(id) ON DELETE CASCADE,
  from_status text        NOT NULL
                          CHECK (from_status IN ('unpacking_sorting', 'sorted', 'lotting', 'ready', 'pickup', 'completed')),
  to_status   text        NOT NULL
                          CHECK (to_status   IN ('unpacking_sorting', 'sorted', 'lotting', 'ready', 'pickup', 'completed')),
  -- user_id uuid REFERENCES auth.users(id)  -- uncomment when auth is added
  created_at  timestamptz NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  rack_events            IS 'Immutable log of rack status transitions.';
COMMENT ON COLUMN rack_events.from_status IS 'Status the rack left. Maps to HistoryEvent.from in TypeScript.';
COMMENT ON COLUMN rack_events.to_status   IS 'Status the rack entered. Maps to HistoryEvent.to in TypeScript.';
COMMENT ON COLUMN rack_events.created_at  IS 'Maps to HistoryEvent.timestamp in TypeScript.';


-- ── Indexes ───────────────────────────────────────────────────────────────────
-- Only indexes that serve real query patterns in the app.

-- Dashboard counts and lotting queue filter
CREATE INDEX IF NOT EXISTS idx_racks_status      ON racks(status);

-- Zone detail page — "all racks in zone X"
CREATE INDEX IF NOT EXISTS idx_racks_zone_id     ON racks(zone_id);

-- Delivery detail page — "all racks in delivery X"
CREATE INDEX IF NOT EXISTS idx_racks_delivery_id ON racks(delivery_id);

-- Primary lookup for time tracking (getStatusEntryTime, getStageDurations)
CREATE INDEX IF NOT EXISTS idx_rack_events_rack_id    ON rack_events(rack_id);

-- Time-range queries for bottleneck detection at the DB level (future use)
CREATE INDEX IF NOT EXISTS idx_rack_events_created_at ON rack_events(created_at);

-- Active delivery filtering
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON deliveries(status);


-- ════════════════════════════════════════════════════════════════════════════
-- FUNCTION: advance_rack_status(rack_id, to_status)
-- Atomically updates the rack's status AND inserts an event record.
-- Called via supabase.rpc('advance_rack_status', { ... })
-- This must be atomic — a partial write (status updated, event missing)
-- breaks the time-tracking logic in lib/timeTracking.ts.
-- ════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION advance_rack_status(
  p_rack_id   uuid,
  p_to_status text
)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  v_from_status text;
BEGIN
  -- Read current status (also acts as a row lock for the duration)
  SELECT status INTO v_from_status
  FROM racks
  WHERE id = p_rack_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Rack % not found', p_rack_id;
  END IF;

  IF v_from_status = 'completed' THEN
    RAISE EXCEPTION 'Rack % is already completed', p_rack_id;
  END IF;

  -- Update rack status (updated_at handled by trigger)
  UPDATE racks
  SET status = p_to_status
  WHERE id = p_rack_id;

  -- Insert immutable event record
  INSERT INTO rack_events (rack_id, from_status, to_status)
  VALUES (p_rack_id, v_from_status, p_to_status);
END;
$$;

COMMENT ON FUNCTION advance_rack_status IS
  'Atomically advances a rack to the next status and records the transition event.';


-- ════════════════════════════════════════════════════════════════════════════
-- RELATIONSHIP SUMMARY
--
--   zones ──────────────────────────── racks.zone_id
--                                         ON DELETE SET NULL
--
--   deliveries ─────────────────────── racks.delivery_id
--                                         ON DELETE SET NULL
--
--   racks ──────────────────────────── rack_events.rack_id
--                                         ON DELETE CASCADE
--
-- Cardinality:
--   delivery  1 ──── * racks        (one delivery has many racks)
--   zone      1 ──── * racks        (one zone holds many racks)
--   rack      1 ──── * rack_events  (one rack has many events)
-- ════════════════════════════════════════════════════════════════════════════


-- ── RLS — currently disabled (run Phase 1 RLS block below after auth is live) ─

ALTER TABLE zones       DISABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries  DISABLE ROW LEVEL SECURITY;
ALTER TABLE racks       DISABLE ROW LEVEL SECURITY;
ALTER TABLE rack_events DISABLE ROW LEVEL SECURITY;


-- ════════════════════════════════════════════════════════════════════════════
-- PHASE 1 RLS — run in Supabase SQL editor AFTER auth is confirmed working.
-- Grants full access to any authenticated user (warehouse staff share data).
-- ════════════════════════════════════════════════════════════════════════════

-- ALTER TABLE zones       ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE deliveries  ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE racks       ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE rack_events ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY "authenticated" ON zones       FOR ALL USING (auth.role() = 'authenticated');
-- CREATE POLICY "authenticated" ON deliveries  FOR ALL USING (auth.role() = 'authenticated');
-- CREATE POLICY "authenticated" ON racks       FOR ALL USING (auth.role() = 'authenticated');
-- CREATE POLICY "authenticated" ON rack_events FOR ALL USING (auth.role() = 'authenticated');
